# Setup -----------------------------------------------------------------------------------------
rm(list = ls())
invisible(gc())
options(stringsAsFactors = F)

library(dplyr)
library(ggplot2)
library(purrr)
library(plotly)
library(htmlwidgets)

# data --------------------------------------------------------------------
txtfile <- "txtfile generated by 1_readlen_qua.py"
df <- read.csv(txtfile, header = T, sep = "\t", comment.char = '')

df <- df %>%
  mutate(
    Short_Samples_Barcodes = gsub("barcode", "bc", `Samples.Barcodes.`) 
  )
df <- df %>%
  mutate(Name_Combined = paste0(Experiment_ID, "_", Short_Samples_Barcodes, "_", Location))

# IQR outlier -----------------------------------------------------------------
calculate_bounds <- function(x) {
  Q1 <- quantile(x, 0.25)
  Q3 <- quantile(x, 0.75)
  IQR <- Q3 - Q1
  lower_bound <- Q1 - 1.5 * IQR
  upper_bound <- Q3 + 1.5 * IQR
  return(list(lower_bound = lower_bound, upper_bound = upper_bound))
}

df <- df %>%
  group_by(Name_Combined) %>%
  mutate(
    bounds = list(calculate_bounds(Read_length)),
    lower_bound = map_dbl(bounds, "lower_bound"),
    upper_bound = map_dbl(bounds, "upper_bound"),
    Is_Outlier = Read_length < lower_bound | Read_length > upper_bound
  ) %>%
  ungroup() %>%
  select(-bounds)

df_woOutliers <- df %>%
  filter(Is_Outlier == "FALSE")

colors <- c("NHM 30m" = "#e31a1c", "NHM 15m" = "#e31a1c", "NHM 0m" = "#e31a1c", 
            "Vauxhall" = "#ff7f00", "Pimlico" = "#fdbf6f",
            "Victoria" = "#F4D03F", "St. James’s Park" = "#ffff99", "Water blank" = "#99A3A4",
            "Regent’s Park" = "#33a02c", "St. Mary’s Hospital" = "#b2df8a", "Marylebone" = "#48C9B0",
            "Piccadilly" = "#1f78b4", "Trafalgar Square" = "#a6cee3", "Embankment" = "#6a3d9a",
            "Monument" = "#cab2d6", "Liverpool Street" = "#F2A6C9")


# plots for read length --------------------------------------------------------
plot_violin <- ggplot(df, aes(x = Name_Combined, y = Read_length, fill = Location)) +
  geom_violin(trim = FALSE) + 
  scale_fill_manual(values = colors) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Read Length Distribution for Each Sample", x = "Sample", y = "Read Length") +
  ylim(0, max(df_woOutliers$Read_length, na.rm = TRUE))
ggsave("Read_length_violin.pdf", plot = plot_violin, width = 20, height = 18)


